name: WolfHunt
main: me.Kruithne.WolfHunt.WolfHunt
version: 1.1
author: Kruithne
description: Allows players to hunt each other with Wolves.
commands:
  regionextras:
    description: WolfHunt commands
    usage: /wolfhunt [command] [parameter]
    aliases: [wh]